CPUS="1"
MEMORY="1024"
VAGRANT_HOSTNAME="puppet-master"

$script = <<SCRIPT
#!/bin/bash
# support RPM for puppetserver installation
rpm -Uvh https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm

# puppet installation plus some otherr utilities
yum install -y puppetserver git

sed -i 's#\-Xms2g#\-Xms512m#g;s#\-Xmx2g#\-Xmx512m#g' /etc/sysconfig/puppetserver

systemctl start puppetserver
systemctl enable puppetserver

echo -e "\n[agent]\nserver = $1.puppet.vm" >> /etc/puppetlabs/puppet/puppet.conf

sed -i 's#PATH=.*#PATH=$PATH:/opt/puppetlabs/puppet/bin:$HOME/bin#g' ~/.bash_profile

/opt/puppetlabs/puppet/bin/gem install r10k

mkdir /etc/puppetlabs/r10k/

echo -e "---
:cachedir: '/var/cache/r10k'

:sources:
        :my-org:
                #remote: 'https://github.com/avillalobos/lsst_devops.git'
                remote: 'https://github.com/lsst/itconf_l1ts.git'
                basedir: '/etc/puppetlabs/code/environments'" > /etc/puppetlabs/r10k/r10k.yaml

echo -e "\n10.0.0.254\t puppet-master.puppet.vm\tpuppet-master" >> /etc/hosts

# Download latest version of the develop branch on the itconf_l1ts repo
/opt/puppetlabs/puppet/bin/r10k deploy environment develop -t

mkdir -p /etc/puppetlabs/code/environments/production

# Due some issues with the puppet-archive being on the environment, this module is installed to be available for all the environments, but this is not required, is just a hack to make the puppet server work.
/opt/puppetlabs/bin/puppet module install puppet-archive --target-dir=/etc/puppetlabs/code/modules 

# Deploy the profile that belongs to the puppet server itself
/opt/puppetlabs/bin/puppet agent -t --environment develop
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = VAGRANT_HOSTNAME + ".puppet.vm"
  config.vm.provision "shell" do |s|
    s.inline = $script
    s.args = VAGRANT_HOSTNAME
  end
  config.vm.network "private_network", ip: "10.0.0.254"
  config.vm.provider "virtualbox" do |v|
    v.name = VAGRANT_HOSTNAME + ".puppet.vm"
    v.memory = MEMORY
    v.cpus = CPUS
  end

end
